### ISSUE TITLE
импорт мешей

### ISSUE THREAD

**Issue by PiratBuildov** [ivanBel97/blender-metro-2033#1]
В окне импорта указано, что можно импортировать .model и .mesh, но на самом деле импортировать можно только .model. Когда будет поддержка .mesh?

**Comment by ivanBel97** [comment]
Уже сейчас можно, просто надо фильтр поменять! Включи, чтобы все файлы отображались и выбери .mesh - это пока экспериментально просто ;) В новом апдейте сделаю фикс данного бага!
